apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  interval: 1h
  releaseName: tailscale-operator
  targetNamespace: tailscale
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: tailscale-operator
      version: 1.102.3
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    # The chart uses the pre-created tailscale/operator-oauth Secret by default.
    ingressClass:
      enabled: true
      name: tailscale
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 1h
  releaseName: csi-driver-nfs
  targetNamespace: kube-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.13.4
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
        namespace: flux-system
